# -*- coding: utf-8 -*-
"""NewGrpAssessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3UOU7g2NDcV8bq6lZ7hK2jOx4cl2g6Q

# **Task 2: Data Engineering & Preparation.**
"""

import pandas as pd
import numpy as np

# 1. Load the datasets using your absolute paths
df_petrol = pd.read_csv('/content/country_petrol_2020_2026.csv')
df_crude = pd.read_csv('/content/crude_oil_2020_2026.csv')

from google.colab import drive
drive.mount('/content/drive')

# 3. Data Transformation (Aggregating)
# We calculate the average global crude price for each month
df_crude_monthly = df_crude.groupby(['Year', 'Month']).agg({
    'Brent_USD': 'mean'
}).reset_index().rename(columns={'Brent_USD': 'Global_Brent_Avg'})

# 4. Data Merging
# Combine the national petrol prices with global crude benchmarks
df_final = pd.merge(df_petrol, df_crude_monthly, on=['Year', 'Month'], how='left')

# 5. Feature Engineering (New Columns)
# Difference between retail petrol and global raw material cost
df_final['Price_Gap'] = df_final['Petrol_USD'] - (df_final['Global_Brent_Avg'] / 159)

# Calculate Month-over-Month change in petrol price for each country
df_final = df_final.sort_values(by=['Country', 'Date'])
df_final['MoM_Change'] = df_final.groupby('Country')['Petrol_USD'].diff()

print(" STEP 1 SUCCESSFUL!")
print(f"Total records processed: {len(df_final)}")
df_final.head()

"""# **Clean the dataset**:"""

# 1. Fill NaN in MoM_Change with 0 (assuming no change for the first month)
df_final['MoM_Change'] = df_final['MoM_Change'].fillna(0)

# 2. Fill any missing Global Averages with the overall average (if any)
df_final['Global_Brent_Avg'] = df_final['Global_Brent_Avg'].fillna(df_final['Global_Brent_Avg'].mean())

# 3. Final Check
print("Checking for remaining NaNs:")
print(df_final.isnull().sum())

# Show the first few rows - January should now show 0.0 instead of NaN
df_final.head()

"""# **TASK 3: Exploratory Data Analysis**

# **Chart 1: Bar Chart (Regional Comparison)**

This chart compares the average petrol price across different regions. It helps identify which parts of the world face the highest energy costs.
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(data=df_final, x='Region', y='Petrol_USD', palette='viridis', errorbar=None)
plt.title('Average Petrol Price (USD) by Region', fontsize=14)
plt.ylabel('Price in USD per Liter')
plt.xticks(rotation=45)
plt.show()

"""# **Chart 2: Line Chart (Price Trends Over Time)**

This time-series visualization shows how national petrol prices move in relation to global Brent crude oil prices from 2020 to 2026.
"""

plt.figure(figsize=(12, 6))
sns.lineplot(data=df_final, x='Date', y='Petrol_USD', label='National Petrol Price', color='blue')
sns.lineplot(data=df_final, x='Date', y='Global_Brent_Avg', label='Global Brent Avg', color='red', alpha=0.3)
plt.title('Petrol vs. Global Crude Price Trends (2020-2026)', fontsize=14)
plt.ylabel('Price in USD')
plt.legend()
plt.show()

"""# **Chart 3: Histogram (Price Distribution)**

The histogram shows the frequency of different price points. The "KDE" line (the curve) helps us see if the global prices are normally distributed or skewed.
"""

plt.figure(figsize=(10, 6))
sns.histplot(df_final['Petrol_USD'], bins=30, kde=True, color='teal')
plt.title('Frequency Distribution of Global Petrol Prices', fontsize=14)
plt.xlabel('Petrol Price (USD/Liter)')
plt.show()

"""# **Chart 4: Box Plot (Subsidy Impact)**

This chart visualizes the "spread" of prices. It clearly shows how government subsidies effectively lower the median price of petrol compared to non-subsidized countries.

"""

plt.figure(figsize=(8, 6))
sns.boxplot(data=df_final, x='Subsidy', y='Petrol_USD', palette='Set2')
plt.title('Impact of Subsidies on Petrol Retail Price', fontsize=14)
plt.show()

"""# **Chart 5: Scatter Plot (Correlation)**

This plot tests the relationship between raw material (Crude) and the final product (Petrol). A diagonal pattern indicates a strong positive correlation.
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_final, x='Global_Brent_Avg', y='Petrol_USD', hue='Region', alpha=0.6)
plt.title('Correlation: Global Brent Crude vs. Local Petrol Price', fontsize=14)
plt.xlabel('Global Brent Price (USD/Barrel)')
plt.ylabel('Local Petrol Price (USD/Liter)')
plt.show()



"""# **Chart 6: Correlation Heatmap**

This provides a numerical score (from -1 to 1) for how strongly variables relate. A score near 1.0 between Petrol and Crude proves that global markets drive local prices.
"""

plt.figure(figsize=(10, 8))
# We only select numerical columns for the heatmap
numerical_cols = ['Petrol_USD', 'Global_Brent_Avg', 'Price_Gap', 'MoM_Change']
corr = df_final[numerical_cols].corr()

sns.heatmap(corr, annot=True, cmap='RdBu_r', center=0, fmt=".2f")
plt.title('Correlation Matrix of Key Price Metrics', fontsize=14)
plt.show()

"""# **TASK 4: Advanced Visualization & Insight.**

# **1: Interactive Multi-Country Timeline**

This interactive version allows stakeholders to double-click a specific country in the legend to isolate its trend, helping in specific policy analysis for SDG 7
"""

import plotly.express as px

# Create an interactive line chart
fig1 = px.line(df_final,
               x="Date",
               y="Petrol_USD",
               color="Country",
               line_group="Country",
               hover_name="Country",
               title="Advanced Technique 1: Interactive Energy Price Trajectories (2020-2026)",
               labels={"Petrol_USD": "Petrol Price (USD/Liter)", "Date": "Year"},
               template="plotly_white")

# Add a range slider for time exploration
fig1.update_layout(xaxis_rangeslider_visible=True)
fig1.show()

"""Decision-Making Insight: If a policymaker sees a country’s price suddenly spike while the global average (Brent) is stable, they can investigate local supply chain issues or tax changes.

# **2: Global Vulnerability Map (Geospatial)**

It provides an immediate geographical context. We are mapping "Petrol Price" to see which regions are "Hotspots" for energy unaffordability
"""

# Aggregate average price per country for a clean map
map_data = df_final.groupby(['Country', 'ISO', 'Region'])['Petrol_USD'].mean().reset_index()

fig2 = px.choropleth(map_data,
                    locations="ISO",
                    color="Petrol_USD",
                    hover_name="Country",
                    projection="natural earth",
                    color_continuous_scale=px.colors.sequential.Plasma,
                    title="Advanced Technique 2: Geospatial Distribution of Fuel Costs",
                    labels={'Petrol_USD':'Avg Price (USD)'})

fig2.update_layout(margin={"r":0,"t":50,"l":0,"b":0})
fig2.show()

"""High-cost "purple" zones on the map indicate regions where the government might need to implement price ceilings to meet SDG 7 targets for affordable energy.

# **3: Faceted Regional Comparison (Small Multiples)**

"Faceting" splits the chart into multiple sub-plots. It allows us to compare the "Price Gap" (the difference between global crude and local petrol) across different continents side-by-side.
"""

# Faceted Area Chart
fig3 = px.area(df_final,
               x="Date",
               y="Price_Gap",
               color="Region",
               facet_col="Region",
               facet_col_wrap=3,
               title="Advanced Technique 3: Regional 'Price Gap' Analysis (Retail vs Crude)",
               labels={"Price_Gap": "Price Difference (USD)"})

fig3.update_layout(showlegend=False)
fig3.show()

"""Regions with a very small or negative "Price Gap" are likely heavily subsidizing fuel, which is a financial risk for the government's budget long-term.



"""